name: giap-web-cicd

on:
  push:
    branches: [main]
    tags: ['v*']
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'

env:
  BUILD_CONFIGURATION: Release
  SOLUTION_DIRECTORY: DfE.GIAP.All
  IMAGE_BASE: _PLACEHOLDER_

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Required to check out the code.
      packages: read  # Required to access the DfE-Digital NuGet feed.

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET SDK from global.json
        uses: actions/setup-dotnet@v5

      - name: Add DfE-Digital GitHub NuGet Feed Credentials
        run: |
          dotnet nuget update source dfedigital \
            --configfile ./DfE.GIAP.All/nuget.config \
            --username USERNAME \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - name: Verify formatting
        run: |
          dotnet format ${{ env.SOLUTION_DIRECTORY }} \
            --verbosity detailed \
            --verify-no-changes

  build-pr-image:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # required to push to GHCR with GITHUB_TOKEN
    steps:
      - name: Setup .NET SDK from global.json
        uses: actions/setup-dotnet@v5

      - name: Install NuGet tools
        uses: NuGet/setup-nuget@v2

      - name: Restore dotnet tools
        run: dotnet tool restore
        shell: bash

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Add DfE-Digital GitHub NuGet Feed Credentials
        run: |
          dotnet nuget update source dfedigital \
            --configfile ./DfE.GIAP.All/nuget.config \
            --username USERNAME \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - uses: ./.github/actions/image-name
      - run: echo "Pushing to ${IMAGE_BASE}"

      - name: Build & push PR image
        run: |

          # github.head_ref is the source branch for PRs,
          # Normalize: lowercase, replace '/', spaces with '-'

          BRANCH_SAFE="$(echo "${{ github.head_ref }}" | tr '[:upper:]' '[:lower:]' | sed -E 's#[^a-z0-9._-]#-#g')"
          TAG_BRANCH="pr-${BRANCH_SAFE}-${{ github.sha }}"
          TAG_NUM="pr-${{ github.event.number }}-${{ github.sha }}"

          docker buildx build \
            --secret id=nuget_config,src=DfE.GIAP.All/nuget.config \
            -t "${IMAGE_BASE}:${TAG_BRANCH}" \
            -t "${IMAGE_BASE}:${TAG_NUM}" \
            --push .

  build-latest-image:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # required to push to GHCR with GITHUB_TOKEN
    steps:
      - name: Setup .NET SDK from global.json
        uses: actions/setup-dotnet@v5

      - name: Install NuGet tools
        uses: NuGet/setup-nuget@v2

      - name: Restore dotnet tools
        run: dotnet tool restore
        shell: bash

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Add DfE-Digital GitHub NuGet Feed Credentials
        run: |
          dotnet nuget update source dfedigital \
            --configfile ./DfE.GIAP.All/nuget.config \
            --username USERNAME \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - uses: ./.github/actions/image-name
      - run: echo "Pushing to ${IMAGE_BASE}"

      - name: Build & push main image
        run: |
          docker buildx build \
            --secret id=nuget_config,src=DfE.GIAP.All/nuget.config \
            -t ${IMAGE_BASE}:sha-${{ github.sha }} \
            -t ${IMAGE_BASE}:latest \
            --push .

  build-release-image:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # required to push to GHCR with GITHUB_TOKEN
    steps:
      - name: Setup .NET SDK from global.json
        uses: actions/setup-dotnet@v5

      - name: Install NuGet tools
        uses: NuGet/setup-nuget@v2

      - name: Restore dotnet tools
        run: dotnet tool restore
        shell: bash

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Add DfE-Digital GitHub NuGet Feed Credentials
        run: |
          dotnet nuget update source dfedigital \
            --configfile ./DfE.GIAP.All/nuget.config \
            --username USERNAME \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - uses: ./.github/actions/image-name
      - run: echo "Pushing to ${IMAGE_BASE}"

      - name: Build & push release image
        run: |
          docker buildx build \
            --secret id=nuget_config,src=DfE.GIAP.All/nuget.config \
            -t ${IMAGE_BASE}:${{ github.ref_name }} \
            --push .


  build_unittest_package:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Required to check out the code.
      packages: read  # Required to access the DfEDigital NuGet feed.

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build
        uses: ./.github/actions/build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        shell: bash
        run: |

          for proj in \
            ${{ env.SOLUTION_DIRECTORY }}/tests/DfE.GIAP.Core.UnitTests/DfE.GIAP.Core.UnitTests.csproj \
            ${{ env.SOLUTION_DIRECTORY }}/tests/DfE.GIAP.Web.Tests/DfE.GIAP.Web.Tests.csproj
          do
            TEST_PROJECT=$(basename "$proj" .csproj)

            #absolute so coverlet doesn't output in build-dir for each test project
            OUTPUT_REPORT_PATH="$(pwd)/coverage-unit/$TEST_PROJECT-cobertura.xml"

            echo "Output path for coverage report is $OUTPUT_REPORT_PATH"
            echo "Running tests for $TEST_PROJECT..."

            dotnet test "$proj" \
              --no-build \
              --nologo \
              --logger "console;verbosity=detailed" \
              -p:CollectCoverage=true \
              -p:CoverletOutputFormat=cobertura \
              -p:CoverletOutput="$OUTPUT_REPORT_PATH"
          done

      - name: Upload unit test projects coverage reports
        uses: actions/upload-artifact@v6
        with:
          name: unit-test-coverage
          path: coverage-unit/

      - name: Run gulp
        run: |
          npm install -g gulp
          gulp default --gulpfile src/DfE.GIAP.Web/gulpfile.js --cwd src/DfE.GIAP.Web
        working-directory: ${{ env.SOLUTION_DIRECTORY }}

      - name: Publish application
        run: dotnet publish src/DfE.GIAP.Web/DfE.GIAP.Web.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output ${{ github.workspace }}/publish
        working-directory: ${{ env.SOLUTION_DIRECTORY }}

      - name: Verify publish output
        run: ls -hal ${{ github.workspace }}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v6
        with:
          name: packaged_app_for_deployment
          path: publish
          if-no-files-found: error

  local_integration_tests:
    # TODO Dependabot does not have access to secrets - https://github.com/DFE-Digital/get-information-about-pupils/issues/17#issuecomment-2994486283
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required to check out the code.
      packages: read  # Required to access the DfEDigital NuGet feed.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build
        uses: ./.github/actions/build
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env file
        shell: bash
        run: |
          echo "WIREMOCK_KEYSTORE_STOREPASSWORD=${{ secrets.WIREMOCK_KEYSTORE_STOREPASSWORD }}" >> .env
          echo "WIREMOCK_KEYSTORE_KEYPASSWORD=${{ secrets.WIREMOCK_KEYSTORE_KEYPASSWORD }}" >> .env
          echo "SHARED_CERTIFICATES=./certs" >> .env

      - name: Run Integration Tests with Coverage
        shell: bash
        run: |
          dotnet nuget update source dfedigital \
            --configfile ./DfE.GIAP.All/nuget.config \
            --username USERNAME \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

          export DOCKER_BUILDKIT=1

          # Initcontainer to generate certificates enabling WireMock
          docker compose up --build certgenerator

          # Run tests
          docker compose up cosmosdb wiremock integration-tests \
            --build \
            --abort-on-container-exit \
            --exit-code-from integration-tests

      - name: Upload integration test coverage report
        uses: actions/upload-artifact@v6
        with:
          name: integration-test-coverage
          path: coverage-integration/cobertura.xml

  merge_coverage_reports:
    runs-on: ubuntu-latest
    needs: [build_unittest_package, local_integration_tests]
    permissions:
      contents: read  # Required to check out the code.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET SDK from global.json
        uses: actions/setup-dotnet@v5

      - name: Restore dotnet tools
        run: dotnet tool restore
        shell: bash

      - name: Download unit test coverage reports
        uses: actions/download-artifact@v7
        with:
          name: unit-test-coverage
          path: coverage-unit/

      - name: Download integration test coverage report
      # TODO Dependabot does not have access to secrets - https://github.com/DFE-Digital/get-information-about-pupils/issues/17#issuecomment-2994486283
        if: github.actor != 'dependabot[bot]'
        uses: actions/download-artifact@v7
        with:
          name: integration-test-coverage
          path: coverage-integration/

      - name: Normalize coverage paths
        run: |
          sed -i 's|/app/DfE.GIAP.All/src/|DfE.GIAP.All/src/|' coverage-integration/cobertura.xml

          # multiple files need to be normalised
          find coverage-unit/ -name "*.xml" -exec sed -i "s|${{ github.workspace }}/DfE.GIAP.All/src/|DfE.GIAP.All/src/|" {} +

      - name: Merge coverage reports
        run: |
          dotnet tool run reportgenerator \
            -sourcedirs:"." \
            -reports:"coverage-unit/**/*.xml;coverage-integration/**/*.xml" \
            -reporttypes:SonarQube \
            -targetdir:"merged-coverage-reports/" \
            -assemblyfilters:"-DfE.GIAP.Web.Views"

      - name: Upload merged coverage report to SonarQube
        uses: actions/upload-artifact@v6
        with:
          name: merged-coverage-report
          path: merged-coverage-reports/SonarQube.xml

  sonarcloud_scan:
    runs-on: ubuntu-latest
    needs: merge_coverage_reports

    permissions:
      contents: read  # Required to check out the code.
      packages: read  # Required to access the DfEDigital NuGet feed.

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download merged coverage report
        uses: actions/download-artifact@v7
        with:
          name: merged-coverage-report
          path: merged-coverage-reports

      - name: Add DfE NuGet Feed
        run: |
          dotnet nuget update source dfedigital \
            --configfile ./DfE.GIAP.All/nuget.config \
            --username USERNAME \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - name: Restore NuGet packages
        run: dotnet restore ./DfE.GIAP.All/*.sln --configfile ./DfE.GIAP.All/nuget.config

      - name: SonarCloud scan
        if: github.actor != 'dependabot[bot]'
        uses: DFE-Digital/github-actions/sonarscan-dotnet@fb860bd4a4ec0741de4858926f9379f50d542ff8
        with:
          sonarcloud-project-key: DFE-Digital_get-information-about-pupils
          sonarcloud-token: ${{ secrets.SONAR_TOKEN }}
          use-global-json: true
          coverage-report-path: merged-coverage-reports/SonarQube.xml
          sonarscan-args: >
            /d:sonar.scanner.scanAll=false
          build-command: dotnet build ./DfE.GIAP.All/*.sln --no-restore --no-incremental


  ## Below are the "deployment" jobs.
  ## Notes:
  ## - Deployments are (currently) run only on pushes to the main branch, not PRs/tags/release branches.
  ## - These checks are done at the deployment job only - tests (smoke or otherwise) then depend on this deployment, therefore inherit the restrictions
  ## - Concurrency is defined per-environment (allows full deployment/test to complete, before allowing later queued runs to continue).
  ## - Permissions are explicit on each job, ensuring only the minimum required permissions are granted.
  ## - Smoke tests are deliberately extremely lightweight to check the app is deployed and running at all without signs of Azure errors (i.e., they do not check that it is running _correctly_).


  ####
  ## Development Environment
  ####
  deploy_development:
    needs: [build_unittest_package, lint, local_integration_tests]
    concurrency:
      group: deploy-and-test-dev
    permissions:
      contents: read  # Required to check out the code.
      id-token: write # Required for OIDC authentication with Azure
    runs-on: ubuntu-latest
    environment: development
    outputs:
      app_url: ${{ steps.deploy.outputs.app_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy to Azure
        id: deploy
        uses: ./.github/actions/deploy
        with:
          app_name: s115d10-as-searchweb-cs
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  verify_development:
    needs: deploy_development
    concurrency:
      group: deploy-and-test-dev
    permissions:
      contents: read  # Required to check out the code.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run smoke tests
        uses: ./.github/actions/smoke-test
        with:
          url: ${{ needs.deploy_development.outputs.app_url }}

  ####
  ## Test Environment
  ####
  deploy_test:
    needs: verify_development
    concurrency:
      group: deploy-and-test-test
      cancel-in-progress: true
    permissions:
      contents: read  # Required to check out the code.
      id-token: write # Required for OIDC authentication with Azure
    runs-on: ubuntu-latest
    environment: test
    outputs:
      app_url: ${{ steps.deploy.outputs.app_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy to Azure
        id: deploy
        uses: ./.github/actions/deploy
        with:
          app_name: s115t02-as-searchweb-cs
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  verify_test:
    needs: deploy_test
    concurrency:
      group: deploy-and-test-test
    permissions:
      contents: read  # Required to check out the code.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run smoke tests
        uses: ./.github/actions/smoke-test
        with:
          url: ${{ needs.deploy_test.outputs.app_url }}

  publish_github_release:
    needs: [verify_test]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ####
  ## Pre-Production Environment
  ####

  deploy_preprod:
    needs: verify_test
    concurrency:
      group: deploy-and-test-preproduction
      cancel-in-progress: true
    permissions:
      contents: read  # Required to check out the code.
      id-token: write # Required for OIDC authentication with Azure
    runs-on: ubuntu-latest
    environment: preproduction
    outputs:
      app_url: ${{ steps.deploy.outputs.app_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy to Azure
        id: deploy
        uses: ./.github/actions/deploy
        with:
          app_name: s115p02-as-searchweb-cs
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  verify_preprod:
    needs: deploy_preprod
    concurrency:
      group: deploy-and-test-preproduction
    permissions:
      contents: read  # Required to check out the code.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run smoke tests
        uses: ./.github/actions/smoke-test
        with:
          url: ${{ needs.deploy_preprod.outputs.app_url }}

  ####
  ## Production Environment
  ####
  deploy_prod:
    needs: verify_preprod
    concurrency:
      group: deploy-and-test-production
    permissions:
      contents: read  # Required to check out the code.
      id-token: write # Required for OIDC authentication with Azure
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: production
    outputs:
      app_url: ${{ steps.deploy.outputs.app_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Deploy to Azure
        id: deploy
        uses: ./.github/actions/deploy
        with:
          app_name: s115p01-as-searchweb-cs
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  verify_prod:
    needs: deploy_prod
    concurrency:
      group: deploy-and-test-production
    permissions:
      contents: read  # Required to check out the code.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run smoke tests
        uses: ./.github/actions/smoke-test
        with:
          url: ${{ needs.deploy_prod.outputs.app_url }}
